# Obtener todos usuarios
GET http://127.0.0.1:5001/api/Usuarios HTTP/1.2

### Busqueda de usuarios

GET http://127.0.0.1:5001/api/Usuarios/buscar/marlon/paola%20vega%20chacon HTTP/1.2
Content-Type: application/json

### Crear un usuario
POST http://127.0.0.1:5001/api/Usuarios HTTP/2.0
Content-Type: application/json

{
    "User": "mvega",
    "Password": "ONCEdeENERO",
    "Nombre": "Marlon",
    "Apellido1": "Vega",
    "Apellido2": "Chinchilla",
    "FechaNacimiento": "1999-01-11",
    "Nacionalidad": "Salvadoreño",
    "Foto": "",
    "EsOrganizador": false
}

### Seguir a un usuario
POST http://127.0.0.1:5001/api/Amigos HTTP/2.0
Content-Type: application/json

{
    "User": "mvega",
    "AmigoUser": "pvill"
}